algoritmo "trabalho"
var
DIAS_TRAB: Inteiro
SAL: Real
inicio
Escreval ("|========================BEM-VINDO=========================|")
Escreva (" DIGITE OS NUMERO DE DIAS TRABALHADOS: ")
Leia (DIAS_TRAB)
SAL<-DIAS_TRAB*(8*25)
Escreval (" O SALARIO REFERENTE A: ",DIAS_TRAB," DIAS DE TRABALHO É DE : ",SAL," R$")
Escreval ("|=========================OBRIGADO=========================|")
fimalgoritmo



