algoritmo "aposentadoria"

var
ANO_ATUAL, ANO_NASC, ANO_EMPRESA, TEMP_TRAB, IDADE: Inteiro

inicio
Escreva ("DIGITE O ANO DE NASCIMENTO: ")
Leia(ANO_NASC)
IDADE<-(2022-ANO_NASC)
Escreva ("DIGITE O ANO DE ADMISSÃO NA EMPRESA: ")
Leia(ANO_EMPRESA)

TEMP_TRAB<-(2022-ANO_EMPRESA)

Se (IDADE>=65) ou (TEMP_EMPRESA>=30)) entao
   escreva ("VOCE PODE SE APOSENTAR A PARTIR DA DATA DO SEU ANIVERSÁRIO!")
Senao
se ((idade>=60) e (TEM_TRAB>=25)) entao

fimalgoritmo
