algoritmo "conversor"
var
N: Real
inicio
Escreva ("DIGITE A DISTANCIA EM METROS: ")
 Leia (N)
Escreval (" ")

Escreval ("A DISTANCIA DE ", N, " METROS CORRESPONDE A:")
 Escreval (N/1000, " Km")
  Escreval (N/100, " Hm")
   Escreval (N/10, " Dam")
    Escreval (N*10, " dm")
     Escreval (N*100, " cm")
      Escreval (N*1000, " mm")
       Escreval (" ")
Escreva ("------------------OBRIGADO------------------ ")
fimalgoritmo
